DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    "NAME" TEXT,
    "DESCRIPTION" TEXT
);

CREATE TABLE PRODUCT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    "NAME" TEXT,
    "DESCRIPTION" TEXT,
    PRICE DOUBLE,
    CATEGORYID INT,
    FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(ID) ON DELETE CASCADE
);