-- Drop tables if they exist (optional, for safety during development)
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS PRODUCT;

-- Create PRODUCT table
CREATE TABLE PRODUCT (
    PRODUCTID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCTNAME TEXT,
    PRICE DOUBLE
);

-- Create REVIEW table with foreign key constraint
CREATE TABLE REVIEW (
    REVIEWID INT PRIMARY KEY AUTO_INCREMENT,
    REVIEWCONTENT TEXT,
    RATING INT,
    PRODUCTID INT,
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID) ON DELETE CASCADE
);
